name: extension_notas_flutter_chorme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-149.0.dev

dependencies:
  analyzer: ^6.11.0
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  validatorless: ^1.2.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
